### ISSUE TITLE
How can pomos be treated like a form of funding in the Pool ?

### ISSUE THREAD

**Issue by inverted-capital** [dreamcatcher-tech/dreamcatcher-tech.github.io#33]
Somehow the pomos we invest need to be tracked the same as money.

I'm thinking we keep the logs, since that shows the day by day breakdown of where we invested out time, then at the end of each day we add the pomos we invested into the running tally against whichever NFTs we were working on.

**Comment by inverted-capital** [comment]
Is a pomo from the same person, on the same project, considered fungible ?

**Comment by TemperBead** [comment]
On the first question, I reckon it's a reasonable proxy for effort.  It's not ideal at scale, because not all pomos between people are equivalent, and even between the same person on different days, but there's a limit to the granularity here, and other than having a multiplier based on previous work or reputation, don't have a good proposal for anything else.

On the question about the fungibility of pomos, yes, but don't see that as a problem.  My laptop hours here could also be tracked and are fungible.  The main point is that they're involved in creating a non-fungible output.  

So for now I think, all we have is recording effort (time, fungible) against output (non-fungible).  There may well be a better way, but practically probably not right now.

**Comment by inverted-capital** [comment]
I think this is closed because we now have a tracking column in [the pool](https://github.com/dreamcatcher-tech/dreamcatcher-tech.github.io/blob/c45f98b77ad74be61e39fa78a6196a65c0d5d94a/website/pool/Market.md) which records pomos as contributions towards a Request, and Idea, or the Asset of an Idea.
